version: '3.4'
services:
  image-storage:
    container_name: image-storage
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT = ${PORT}
    ports:
      - 3333:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/local/apps/image-storage/
      - ignore:/usr/local/apps/image-storage/node_modules/
volumes:
  ignore: